# -*- coding: utf-8 -*-
"""prova-aula05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166BunMd9o0Y4BFDCbEaBKCPVcKto1S7I
"""

# Prova Aula-05
# Crie uma lista contendo seis frutas de sua escolha. Depois de ter a lista pronta, converta essa lista em uma tupla.
# Por fim, exiba o conteúdo da tupla resultante para verificar as frutas que foram armazenadas.

frutas = ['banana', 'maça', 'pera', 'uva', 'laranja', 'pitaya']

frutas_tupla = tuple(frutas)

print(frutas_tupla)